name: Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - v0.18.0-alpha
      - v0.18.0-Alpha
      - v0.18.0-Alpha-rc

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build release
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: owerlayer-windows
          path: target/release/owerlayer.exe

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/owerlayer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
